//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class diseños
    {
        public string Design_id { get; set; }
        public int Description_id { get; set; }
        public string Description_std { get; set; }
        public int Tipo_id { get; set; }
        public Nullable<int> Unidad_id_Purchase { get; set; }
        public Nullable<int> Unidad_id_Aplication { get; set; }
        public System.DateTime Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public System.DateTime Last_Upd { get; set; }
        public string Usr_Upd { get; set; }
        public string User_upd { get; set; }
    }
}
