//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class externos
    {
        public int Ext_id { get; set; }
        public int Tipo_ext_id { get; set; }
        public Nullable<int> Description_id { get; set; }
        public string CUIT { get; set; }
        public int Direccion_id { get; set; }
        public int Direccion_ent_id { get; set; }
        public int Direccion_fac_id { get; set; }
        public string Nac_Ext { get; set; }
    }
}
