//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public int Role_id { get; set; }
        public int Description_id { get; set; }
    }
}
